# Generated by Django 4.2 on 2023-05-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_tweet_user_tweet_retweets_tweet_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='creator',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
