# Generated by Django 4.2 on 2023-05-09 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0012_tweet_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='retweets',
            new_name='retweet_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='users',
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweeters',
            field=models.ManyToManyField(to='main_app.profile'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
