# Generated by Django 4.2 on 2023-05-09 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0013_rename_retweets_tweet_retweet_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='retweet_count',
            new_name='retweets',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweeters',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
        migrations.AddField(
            model_name='tweet',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
